### ISSUE TITLE
Draw to world scale and coordinates

### ISSUE THREAD

**Issue by adam-law** [adam-arold/hexameter#3]
Hi, 

I stumbled upon your excellent work here, thinking to use it on my project. After spending a day tinkering with it, I sadly concluded that it may not be possible, since it seems to be based on a pixel format.

I'm using LibGDX where my game world is logically scaled to 1 world unit: 32 pixels. When I try to render a grid, for example, 100 world units long and wide, with a radius of 0.7, the library fails to resolve the hexes, drawing lines and triangles of what I think are what's supposed to be the hex. I have to use the pixel size, to get it to draw, but then, the hexes and grid are too large. The only way I got things to draw at the appropriate scale is to affect the polygon drawer, scaling its matrix down, to draw smaller.

Needless to say, while I finally got the grid to draw to size, the rest of the library can't work under these conditions. Stuff such as getting the grid coordinates, or coordinates through pixel, resolve wrongly due to the scaling, especially getting the center of each hex, which I need to properly place objects within hexes.

I know it's likely a lot of work on your part, so this is just a suggestion to have the library be able to use world coordinates, instead of pixels units. Most, if not all, game development frameworks strongly urge developing under world coords, to simplify development, and not have to worry about resolution etc, across platforms such as mobile devices. This would make your library a perfect fit as a drop-in solution for Java-based game dev, as there aren't any existing solutions out there, and people have to, basically, roll their own.

After saying all this, I realize that, if this works for Android dev, it might already have a means to work in world scale. If so, please advise.

Thanks, and great job regardless!

**Comment by adam-arold** [comment]
Hi there,

Can we speak about this in more detail? I've never done any game development so far but I'm willing to put the work in if you think it would be more useful. Sorry for the late reply I was not working actively on the project but there were some forks/pull requests and I'll do a major refactor in the near future.

Do you have a Skype or a Hangouts account?
